export interface IproductWrap {
  products: Iproduct[];
}
export interface Iproduct {
  productId: number;
  productName: string;
  productImage: string;
  productImageOrigin: string;
  originalPrice: number;
  discountedPrice: number;
  discountRate: number;
  groupDiscountDisplayable: boolean;
  groupDiscountStatus: string;
  groupDiscountedPrice: number;
  groupDiscountWillClosed: boolean;
  groupDiscountUserCount: number;
  groupDiscountStartAt: number;
  groupDiscountEndAt: number;
  alarmDisplaying: boolean;
  groupDiscountRemainSeconds: number;
  storeId: number;
  storeName: string;
  storeDomain: string;
  storeProfileImage: string;
  new: boolean;
  linkPath: string;
  storeLinkPath: string;
  plusFriendSubscriberExclusive: boolean;
  farmer: boolean;
  deliveryFeeType: string;
  freeDelivery: boolean;
  reviewCount: number;
  productPositivePercentage: number;
  imageRatio: string;
  displayedSaleStatus: string;
  categoryId: string;
  categoryName: string;
  hasAdditionalOptionPrice: true;
  groupDiscountPeriod: { from: string; to: string };
  profiles: string[];
  totalSaleCount: number;
  trackId: string;
  contentId: number;
  contentDisplayPeriod: { from: string; to: string };
  type: string;
  landingUrl: string;
  mainCopy: string;
  label: string;
  imageUrl: string;
  imageUrlOrigin: string;
  sharingImageUrl: string;
  logoImageUrl: string;
  contentRemainDays: number;
  remainDays: number;
  contentOpenDt: string;
  contentCloseDt: string;
  likeProductCount: number;
  isLiked: boolean;
  score: number;
}
